export const UPDATE_SONG_DATA  = 'UPDATE_SONG_DATA'
export const UPDATE_SONG_LYRIC = 'UPDATE_SONG_LYRIC'
export const UPDATE_SONG_INFO  = 'UPDATE_SONG_INFO'
export const UPDATE_PLAY_STATE = 'UPDATE_PLAY_STATE'